name: Wiki

on:
  gollum

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Slack
        run: |
          curl -X POST -H 'Content-type: application/json' \ --data "{\"text\": \"Wiki ${ACTION}: ${TITLE}\n${URL}\"}" \ https://hooks.slack.com/services/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
        env:
          ACTION: ${{ github.event.pages[0].action }}
          TITLE: ${{ github.event.pages[0].title }}
          URL: ${{ github.event.pages[0].html_url }}
          
