name: Wiki

on:
  gollum

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' 
          https://hooks.slack.com/services/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
        env:
          ACTION: ${{ github.event.pages[0].action }}
          TITLE: ${{ github.event.pages[0].title }}
          URL: ${{ github.event.pages[0].html_url }}
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
